### ISSUE TITLE
KeyError: 'sentimentBar'

### ISSUE THREAD

**Issue by jzohrab** [shekharchander/tube_dl#10]
I'm downloading a video, https://m.youtube.com/watch?v=HhV_Y8C5YKo, and get the following error:

```
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    download_audio(lin)
  File "main.py", line 27, in download_audio
    yt = Youtube(url).formats.filter_by(only_audio=True)[0]
  File "/Users/jeff/Documents/Projects/pytubedl/venv/lib/python3.8/site-packages/tube_dl/__main__.py", line 75, in __init__
    self.likes, self.dislikes = [i.strip() for i in extraDetails["sentimentBar"]["sentimentBarRenderer"]["tooltip"].split('/')]
```

**Comment by jzohrab** [comment]
Checking closed issues, I saw in #9 that you recommended installing the wheel (https://github.com/shekharchander/tube_dl/issues/9).  That gets past that error, but now runs into another one for video https://www.youtube.com/watch?v=cgvR03wrolY :

```
checking https://www.youtube.com/watch?v=cgvR03wrolY

Traceback (most recent call last):
  File "main.py", line 52, in <module>
    download_audio(lin)
  File "main.py", line 27, in download_audio
    yt = Youtube(url).formats.filter_by(only_audio=True)[0]
  File "/Users/jeff/Documents/Projects/pytubedl/venv/lib/python3.8/site-packages/tube_dl/__main__.py", line 57, in __init__
    self.keywords = videoDetails["keywords"]
KeyError: 'keywords'
```

**Comment by jzohrab** [comment]
Funny, with that video I'm also getting an error in `__main__.py` on this line:

`            itag = stream["itag"]`

The stream here is *occasionally* just a string, and not a dict, as the code expects.  I added some debug info:

```
        for stream in self.streamingData:
            # CHECK FOR WEIRD ISSUE
            if not type(stream) is dict:
                print('  intermittent error, bad stream: ' + stream)
                continue
            itag = stream["itag"]
```

and I get the following nonsense:

<details>
  <summary>Click to expand</summary>

```
  intermittent error, bad stream: h
  intermittent error, bad stream: t
  intermittent error, bad stream: t
  intermittent error, bad stream: p
  intermittent error, bad stream: s
  intermittent error, bad stream: :
  intermittent error, bad stream: /
  intermittent error, bad stream: /
  intermittent error, bad stream: r
  intermittent error, bad stream: 4
  intermittent error, bad stream: -
  intermittent error, bad stream: -
  intermittent error, bad stream: -
  intermittent error, bad stream: s
  intermittent error, bad stream: n
  intermittent error, bad stream: -
  intermittent error, bad stream: a
  intermittent error, bad stream: 5
  intermittent error, bad stream: m
  intermittent error, bad stream: e
  intermittent error, bad stream: k
  intermittent error, bad stream: n
  intermittent error, bad stream: s
  intermittent error, bad stream: y
  intermittent error, bad stream: .
  intermittent error, bad stream: g
  intermittent error, bad stream: o
  intermittent error, bad stream: o
  intermittent error, bad stream: g
  intermittent error, bad stream: l
  intermittent error, bad stream: e
  intermittent error, bad stream: v
  intermittent error, bad stream: i
  intermittent error, bad stream: d
  intermittent error, bad stream: e
  intermittent error, bad stream: o
  intermittent error, bad stream: .
  intermittent error, bad stream: c
  intermittent error, bad stream: o
  intermittent error, bad stream: m
  intermittent error, bad stream: /
  intermittent error, bad stream: v
  intermittent error, bad stream: i
  intermittent error, bad stream: d
  intermittent error, bad stream: e
  intermittent error, bad stream: o
  intermittent error, bad stream: g
  intermittent error, bad stream: o
  intermittent error, bad stream: o
  intermittent error, bad stream: d
  intermittent error, bad stream: p
  intermittent error, bad stream: u
  intermittent error, bad stream: t
  intermittent error, bad stream: ?
  intermittent error, bad stream: i
  intermittent error, bad stream: d
  intermittent error, bad stream: =
  intermittent error, bad stream: o
  intermittent error, bad stream: -
  intermittent error, bad stream: A
  intermittent error, bad stream: E
  intermittent error, bad stream: I
  intermittent error, bad stream: I
  intermittent error, bad stream: w
  intermittent error, bad stream: o
  intermittent error, bad stream: 1
  intermittent error, bad stream: g
  intermittent error, bad stream: w
  intermittent error, bad stream: S
  intermittent error, bad stream: F
  intermittent error, bad stream: a
  intermittent error, bad stream: f
  intermittent error, bad stream: _
  intermittent error, bad stream: u
  intermittent error, bad stream: G
  intermittent error, bad stream: c
  intermittent error, bad stream: a
  intermittent error, bad stream: K
  intermittent error, bad stream: o
  intermittent error, bad stream: B
  intermittent error, bad stream: y
  intermittent error, bad stream: V
  intermittent error, bad stream: J
  intermittent error, bad stream: 8
  intermittent error, bad stream: b
  intermittent error, bad stream: 4
  intermittent error, bad stream: Q
  intermittent error, bad stream: C
  intermittent error, bad stream: -
  intermittent error, bad stream: P
  intermittent error, bad stream: k
  intermittent error, bad stream: V
  intermittent error, bad stream: t
  intermittent error, bad stream: o
  intermittent error, bad stream: q
  intermittent error, bad stream: j
  intermittent error, bad stream: d
  intermittent error, bad stream: U
  intermittent error, bad stream: D
  intermittent error, bad stream: X
  intermittent error, bad stream: M
  intermittent error, bad stream: 3
  intermittent error, bad stream: b
  intermittent error, bad stream: &
  intermittent error, bad stream: s
  intermittent error, bad stream: o
  intermittent error, bad stream: u
  intermittent error, bad stream: r
  intermittent error, bad stream: c
  intermittent error, bad stream: e
  intermittent error, bad stream: =
  intermittent error, bad stream: g
  intermittent error, bad stream: o
  intermittent error, bad stream: o
  intermittent error, bad stream: d
  intermittent error, bad stream: p
  intermittent error, bad stream: u
  intermittent error, bad stream: t
  intermittent error, bad stream: &
  intermittent error, bad stream: r
  intermittent error, bad stream: a
  intermittent error, bad stream: n
  intermittent error, bad stream: g
  intermittent error, bad stream: e
  intermittent error, bad stream: =
  intermittent error, bad stream: 0
  intermittent error, bad stream: -
  intermittent error, bad stream: 4
  intermittent error, bad stream: 9
  intermittent error, bad stream: 9
  intermittent error, bad stream: 9
  intermittent error, bad stream: &
  intermittent error, bad stream: e
  intermittent error, bad stream: x
  intermittent error, bad stream: p
  intermittent error, bad stream: i
  intermittent error, bad stream: r
  intermittent error, bad stream: e
  intermittent error, bad stream: =
  intermittent error, bad stream: 1
  intermittent error, bad stream: 6
  intermittent error, bad stream: 2
  intermittent error, bad stream: 6
  intermittent error, bad stream: 6
  intermittent error, bad stream: 7
  intermittent error, bad stream: 2
  intermittent error, bad stream: 1
  intermittent error, bad stream: 3
  intermittent error, bad stream: 5
  intermittent error, bad stream: &
  intermittent error, bad stream: i
  intermittent error, bad stream: p
  intermittent error, bad stream: =
  intermittent error, bad stream: 1
  intermittent error, bad stream: 0
  intermittent error, bad stream: 4
  intermittent error, bad stream: .
  intermittent error, bad stream: 2
  intermittent error, bad stream: 0
  intermittent error, bad stream: 0
  intermittent error, bad stream: .
  intermittent error, bad stream: 1
  intermittent error, bad stream: 3
  intermittent error, bad stream: 2
  intermittent error, bad stream: .
  intermittent error, bad stream: 1
  intermittent error, bad stream: 7
  intermittent error, bad stream: 6
  intermittent error, bad stream: &
  intermittent error, bad stream: m
  intermittent error, bad stream: s
  intermittent error, bad stream: =
  intermittent error, bad stream: p
  intermittent error, bad stream: m
  intermittent error, bad stream: &
  intermittent error, bad stream: m
  intermittent error, bad stream: m
  intermittent error, bad stream: =
  intermittent error, bad stream: 3
  intermittent error, bad stream: 5
  intermittent error, bad stream: &
  intermittent error, bad stream: p
  intermittent error, bad stream: l
  intermittent error, bad stream: =
  intermittent error, bad stream: 2
  intermittent error, bad stream: 4
  intermittent error, bad stream: &
  intermittent error, bad stream: n
  intermittent error, bad stream: h
  intermittent error, bad stream: =
  intermittent error, bad stream: I
  intermittent error, bad stream: g
  intermittent error, bad stream: p
  intermittent error, bad stream: w
  intermittent error, bad stream: c
  intermittent error, bad stream: j
  intermittent error, bad stream: A
  intermittent error, bad stream: x
  intermittent error, bad stream: L
  intermittent error, bad stream: m
  intermittent error, bad stream: x
  intermittent error, bad stream: h
  intermittent error, bad stream: e
  intermittent error, bad stream: D
  intermittent error, bad stream: A
  intermittent error, bad stream: y
  intermittent error, bad stream: K
  intermittent error, bad stream: g
  intermittent error, bad stream: 8
  intermittent error, bad stream: y
  intermittent error, bad stream: M
  intermittent error, bad stream: T
  intermittent error, bad stream: Y
  intermittent error, bad stream: u
  intermittent error, bad stream: M
  intermittent error, bad stream: j
  intermittent error, bad stream: I
  intermittent error, bad stream: x
  intermittent error, bad stream: L
  intermittent error, bad stream: j
  intermittent error, bad stream: E
  intermittent error, bad stream: 1
  intermittent error, bad stream: N
  intermittent error, bad stream: i
  intermittent error, bad stream: 4
  intermittent error, bad stream: x
  intermittent error, bad stream: O
  intermittent error, bad stream: D
  intermittent error, bad stream: U
  intermittent error, bad stream: &
  intermittent error, bad stream: s
  intermittent error, bad stream: p
  intermittent error, bad stream: a
  intermittent error, bad stream: r
  intermittent error, bad stream: a
  intermittent error, bad stream: m
  intermittent error, bad stream: s
  intermittent error, bad stream: =
  intermittent error, bad stream: i
  intermittent error, bad stream: d
  intermittent error, bad stream: ,
  intermittent error, bad stream: s
  intermittent error, bad stream: o
  intermittent error, bad stream: u
  intermittent error, bad stream: r
  intermittent error, bad stream: c
  intermittent error, bad stream: e
  intermittent error, bad stream: ,
  intermittent error, bad stream: r
  intermittent error, bad stream: a
  intermittent error, bad stream: n
  intermittent error, bad stream: g
  intermittent error, bad stream: e
  intermittent error, bad stream: ,
  intermittent error, bad stream: e
  intermittent error, bad stream: x
  intermittent error, bad stream: p
  intermittent error, bad stream: i
  intermittent error, bad stream: r
  intermittent error, bad stream: e
  intermittent error, bad stream: ,
  intermittent error, bad stream: i
  intermittent error, bad stream: p
  intermittent error, bad stream: ,
  intermittent error, bad stream: m
  intermittent error, bad stream: s
  intermittent error, bad stream: ,
  intermittent error, bad stream: m
  intermittent error, bad stream: m
  intermittent error, bad stream: ,
  intermittent error, bad stream: p
  intermittent error, bad stream: l
  intermittent error, bad stream: ,
  intermittent error, bad stream: n
  intermittent error, bad stream: h
  intermittent error, bad stream: &
  intermittent error, bad stream: s
  intermittent error, bad stream: i
  intermittent error, bad stream: g
  intermittent error, bad stream: n
  intermittent error, bad stream: a
  intermittent error, bad stream: t
  intermittent error, bad stream: u
  intermittent error, bad stream: r
  intermittent error, bad stream: e
  intermittent error, bad stream: =
  intermittent error, bad stream: 7
  intermittent error, bad stream: 0
  intermittent error, bad stream: 8
  intermittent error, bad stream: E
  intermittent error, bad stream: 7
  intermittent error, bad stream: C
  intermittent error, bad stream: B
  intermittent error, bad stream: A
  intermittent error, bad stream: 9
  intermittent error, bad stream: 3
  intermittent error, bad stream: 5
  intermittent error, bad stream: F
  intermittent error, bad stream: A
  intermittent error, bad stream: E
  intermittent error, bad stream: 4
  intermittent error, bad stream: E
  intermittent error, bad stream: B
  intermittent error, bad stream: 7
  intermittent error, bad stream: A
  intermittent error, bad stream: 7
  intermittent error, bad stream: 5
  intermittent error, bad stream: B
  intermittent error, bad stream: 7
  intermittent error, bad stream: 2
  intermittent error, bad stream: D
  intermittent error, bad stream: B
  intermittent error, bad stream: 1
  intermittent error, bad stream: 5
  intermittent error, bad stream: 4
  intermittent error, bad stream: 0
  intermittent error, bad stream: 8
  intermittent error, bad stream: 2
  intermittent error, bad stream: 9
  intermittent error, bad stream: E
  intermittent error, bad stream: 2
  intermittent error, bad stream: A
  intermittent error, bad stream: 7
  intermittent error, bad stream: F
  intermittent error, bad stream: E
  intermittent error, bad stream: F
  intermittent error, bad stream: .
  intermittent error, bad stream: 7
  intermittent error, bad stream: F
  intermittent error, bad stream: 8
  intermittent error, bad stream: 2
  intermittent error, bad stream: C
  intermittent error, bad stream: C
  intermittent error, bad stream: 1
  intermittent error, bad stream: 1
  intermittent error, bad stream: 8
  intermittent error, bad stream: 5
  intermittent error, bad stream: 0
  intermittent error, bad stream: 2
  intermittent error, bad stream: 8
  intermittent error, bad stream: E
  intermittent error, bad stream: 5
  intermittent error, bad stream: 7
  intermittent error, bad stream: 7
  intermittent error, bad stream: E
  intermittent error, bad stream: 2
  intermittent error, bad stream: F
  intermittent error, bad stream: C
  intermittent error, bad stream: B
  intermittent error, bad stream: D
  intermittent error, bad stream: 9
  intermittent error, bad stream: 4
  intermittent error, bad stream: 7
  intermittent error, bad stream: 8
  intermittent error, bad stream: 6
  intermittent error, bad stream: 0
  intermittent error, bad stream: C
  intermittent error, bad stream: D
  intermittent error, bad stream: E
  intermittent error, bad stream: D
  intermittent error, bad stream: 8
  intermittent error, bad stream: 2
  intermittent error, bad stream: 5
  intermittent error, bad stream: 9
  intermittent error, bad stream: F
  intermittent error, bad stream: 5
  intermittent error, bad stream: B
  intermittent error, bad stream: &
  intermittent error, bad stream: k
  intermittent error, bad stream: e
  intermittent error, bad stream: y
  intermittent error, bad stream: =
  intermittent error, bad stream: c
  intermittent error, bad stream: m
  intermittent error, bad stream: s
  intermittent error, bad stream: 1
```

</details>

Not an issue, as I can just skip that, but thought you might want to know.

**Comment by shekharchander** [comment]
Hi, For me, the streamingdata is always a dictionary. I tried it many times. For the keyword error, you can add exceptions in line #56 in __main__.py. I'll fix them this week.

**Comment by jzohrab** [comment]
Yep, it should be a dict, not sure why it's not ... perhaps a CDN issue.  Who knows!  Thank you.
